### ISSUE TITLE
Use rich domain models

### ISSUE THREAD

**Issue by DevD4v3** [jdaniel1987/GamesShop.CQRS#2]
What do you think about using domain models with behaviors?

There are two domain models in your project:
https://github.com/jdaniel1987/GameShop.CQRS/blob/47adfafb92ef125560ff3e1d7064d12938589342/GameShop.Domain/Entities/Game.cs#L5-L18

https://github.com/jdaniel1987/GameShop.CQRS/blob/47adfafb92ef125560ff3e1d7064d12938589342/GameShop.Domain/Entities/GameConsole.cs#L5-L16

These domain models are anemic (no behavior). You could also add validations in these models instead of using Fluent Validation.
The problem I have had with Fluent Validation, is that I usually repeat the same validation rules for the CREATE and UPDATE operations.
For example: AddGameCommandValidator and UpdateGameCommandValidator have practically the same validation rules.

**Comment by jdaniel1987** [comment]
I prefer to keep validation outside of domain models and use FluentValidation for input objects, like commands and queries, which are mapped from API endpoint parameters. This way, I ensure that the incoming data is validated before being processed, catching any issues early in the flow. If domain models evolve over time, the validation rules might not match the current state of the data retrieved from the database, so keeping the validation at the input stage provides more flexibility.

Regarding the debate between anemic models and models with behavior, I like to keep files as small and focused as possible. When I need to add logic related to a model, I prefer using extension methods. For instance:
public static GameDto ToGameDto(this Game game) { ... }
This allows for cleaner code usage like:
var game = new Game();
var gameDto = game.ToGameDto();
This is just my preferred approach, but models with behavior are also widely used in Domain-Driven Design. The key is to avoid making your classes too large or too complex.

Having two validators for Add and Update is a valid approach, in my opinion, because they represent different concepts, even if they currently only differ by the presence of an ID. These operations serve distinct purposes, and separating their validation logic provides flexibility for future changes. It's possible that over time, the validation rules for Add and Update will diverge, and having them separated from the start will make it easier to manage and scale. 
However, another valid approach would be to have an **Upsert operation**, instead of Add and Update, with only one command for both operations, if you want to add, make ID = null, but if you want to update, use the correct ID
